apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  # Cluster & Routing Resources
  - ingress.yml

  # Backend Resources
  - backend/aws-secretsmanager.yml
  - backend/deployment.yml
  - backend/service.yml
  - backend/secret-store.yml

  # Frontend Resources
  - frontend/deployment.yml
  - frontend/service.yml

images:
  - name: backend-image
    newName: stenox-backend
    newTag: latest
  - name: frontend-image
    newName: stenox-frontend
    newTag: latest