apiVersion: secretsmanager.services.k8s.aws/v1alpha1
kind: Secret
metadata:
  name: stenox-backend-secrets
  namespace: dev
spec:
  name: stenox/backend/credentials
  description: "Stenox Backend Config and Secrets placeholder"
  
  # Defines the keys. Leave values empty to populate securely in the AWS Console.
  secretString: >-
    {
      "DATABASE_URL": "",
      "SMTP_PASSWORD": "",
      "JWT_SECRET": "",
      "SMTP_HOST": "smtp.gmail.com",
      "SMTP_PORT": "587",
      "SMTP_USER": "",
      "FRONTEND_URL": "http://localhost", 
      "CORS_ORIGINS": "http://localhost,http://127.0.0.1",
      "AWS_S3_BUCKET": "",
      "AWS_REGION": "us-east-1"
    }